name: lundedev-core

services:
  lundedev-core:
    container_name: lundedev-core
    image: vegardlu/lundedev-core:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8085:8080"
