- Infrastructure:
    - Cloudflare:
        icon: cloudflare.png
        href: https://dash.cloudflare.com
        description: Tunnel & DNS
        container: cloudflared
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: https://kuma.lundeberg.cc
        container: uptime-kuma
        widget:
          type: uptimekuma
          url: http://localhost:3001
          slug: default

- Media:
    - Immich:
        icon: immich.png
        href: http://immich.lundeberg.cc
        description: Photo Backup
        container: immich_server

- Automation:
    - Home Assistant:
        icon: home-assistant.png
        href: https://ha.lundeberg.cc
        description: Smart Home Controller
        container: homeassistant
